name: 考拉小T
sub_name: 我身在江湖，江湖却没有关于我的传说
github_url: https://github.com/koalaxiaot

markdown: kramdown
kramdown:
  input: GFM

redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
